name: Create Custom Release

on:
  release:
    types: [created]

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 安装 GitHub CLI
      - name: Install GitHub CLI
        run: sudo snap install gh --classic

      # Step 3: 打包项目为 nexhome.zip
      - name: Create nexhome.zip
        run: |
          zip -r nexhome.zip .

      # Step 4: 使用 GitHub CLI 上传资产
      - name: Upload release asset
        run: |
          gh release upload ${{ github.event.release.tag_name }} nexhome.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
