name: Create Custom Release

## 触发条件：仅当创建 Release 时触发
#on:
#  release:
#    types: [created]
on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 检查目标目录是否存在
      - name: Check if directory exists
        run: |
          if [ ! -d "${{ github.workspace }}/custom_components/nexhome" ]; then
            echo "Directory does not exist!"
            exit 1
          fi

      # Step 3: 打印目标目录内容
      - name: List directory contents
        run: |
          ls -la "${{ github.workspace }}/custom_components/nexhome"

      # Step 2: 打包项目为 nexhome.zip
      - name: Create nexhome.zip
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/nexhome"
          zip nexhome.zip -r ./

      # Step 3: 上传 nexhome.zip 到 Release
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: "nexhome.zip"
          token: ${{ secrets.PAT_TOKEN }}
